name: mallxx_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  flutter_lints: ^1.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  easy_refresh: ^3.0.2+2
  card_swiper: ^2.0.4
  flutter_staggered_grid_view: ^0.4.0
  flutter_screenutil: ^5.6.0
  oktoast: ^3.2.0
  flutter_widget_from_html: ^0.8.5
  photo_view: ^0.14.0
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.12
  badges: ^2.0.3
  url_launcher: ^6.1.5
  flutter_easyloading: ^3.0.3
  get: 4.6.5
  getwidget: ^3.0.1
  flutter_pickers: ^2.1.9
  timelines: ^0.1.0
  fluwx: ^3.9.2
  tobias: ^2.4.1
  flutter_asset_generator: ^1.0.2
  image_picker: ^0.8.6
  bruno: 3.1.0
  amap_location_fluttify: ^0.22.0
  permission_handler: 10.2.0
  #  easy_permission: ^1.0.0
  better_video_player:
    path: plugin/better_video_player
  bubble_box: ^0.5.2
  date_time_format: ^2.0.1
  expand_widget: ^2.1.0
  common_utils: ^2.1.0
  auto_orientation: ^2.2.1
  extended_nested_scroll_view: ^5.1.3
  panorama: ^0.4.1
  meiqia_sdk_flutter: ^1.0.1
  city_pickers: ^1.1.3
  lpinyin: ^2.0.3
  #  live_flutter_plugin: ^1.0.14
  get_cli: ^1.8.1
  extended_sliver: 2.1.3
  pin_input_text_field: ^4.2.0
  webview_flutter: ^3.0.4
  jpush_flutter: ^2.4.0
  html_editor_enhanced: ^2.5.0
  video_editor: ^3.0.0
  video_compress: ^3.1.2
  #  ffmpeg_kit_flutter_min: ^5.1.0
  ffmpeg_kit_flutter: ^6.0.2
  fraction: ^4.1.4

  #  flutter_ys7:
  #    path: plugins/flutter_ys7
  #  flutter_localizations:
  #    sdk: flutter
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/tabs/
    - assets/icons/granary/
    - assets/icons/field/
    - assets/icons/mine/
    - assets/icons/market/
    - assets/icons/cart/
  uses-material-design: true
