part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();

  static const ROOT = _Paths.ROOT;
  static const PRODUCT_INFO = _Paths.PRODUCT_INFO;

  //static const PRODUCT_LIST = _Paths.PRODUCT_LIST;
  static const LOGIN = _Paths.LOGIN;
  static const SETTING = _Paths.SETTING;
  static const REGISTER = _Paths.REGISTER;
  static const ADDRESS_BOOK = _Paths.ADDRESS_BOOK;
  static const ACCOUNT_SECURITY = _Paths.ACCOUNT_SECURITY;
  static const PAYMENT_OPTIONS = _Paths.PAYMENT_OPTIONS;
  static const PRIVACY_POLICY = _Paths.PRIVACY_POLICY;
  static const LANGUAGE = _Paths.LANGUAGE;
  static const COUNTRY_REGION = _Paths.COUNTRY_REGION;
  static const ABOUT_ME = _Paths.ABOUT_ME;
  static const ORDER_CONFIRM = _Paths.ORDER_CONFIRM;
  static const ORDER_PAY = _Paths.ORDER_PAY;
  static const ORDER_SUCCESS = _Paths.ORDER_SUCCESS;
  static const MY_ORDER = _Paths.MY_ORDER;
  static const ORDER_DELIVER = _Paths.ORDER_DELIVER;
  static const ORDER_DETAIL = _Paths.ORDER_DETAIL;
  static const COMMENT = _Paths.COMMENT;
  static const COMMENT_DETAIL = _Paths.COMMENT_DETAIL;
  static const MESSAGE_CENTER = _Paths.MESSAGE_CENTER;
  static const MY_COMMENT = _Paths.MY_COMMENT;
  static const LAND_LIST = _Paths.LAND_LIST;
  static const OPERATION_RECORDS = _Paths.OPERATION_RECORDS;
  static const PROCESS = _Paths.PROCESS;
  static const FIELD_DETAIL = _Paths.FIELD_DETAIL;
  static const COMPLAINT_VIEW = _Paths.FIELD_DETAIL + _Paths.COMPLAINT_VIEW;
  static const REAL_TIME_LIST = _Paths.FIELD_DETAIL + _Paths.REAL_TIME_LIST;
  static const LIVE_STREAMING = _Paths.FIELD_DETAIL + _Paths.LIVE_STREAMING;
  static const VR360 = _Paths.FIELD_DETAIL + _Paths.VR360;
  static const REAL_TIME_PLAYER =
      _Paths.FIELD_DETAIL + _Paths.REAL_TIME_LIST + _Paths.REAL_TIME_PLAYER;
  static const SEARCH_VIEW = _Paths.ORDER_SUCCESS + _Paths.SEARCH_VIEW;
  static const GOODS_DETAIL = _Paths.GOODS_DETAIL;
  static const ORDER_CHOOSE_COUPON =
      _Paths.ORDER_CONFIRM + _Paths.ORDER_CHOOSE_COUPON;
  static const ORDER_PAYMENT = _Paths.GOODS_DETAIL + _Paths.ORDER_PAYMENT;
  static const MY_ASSETS = _Paths.GOODS_DETAIL + _Paths.MY_ASSETS;
  static const GUESS_LIKE = _Paths.GOODS_DETAIL + _Paths.GUESS_LIKE;
  static const MY_LIKES = _Paths.GOODS_DETAIL + _Paths.MY_LIKES;
  static const MY_DISLIKES = _Paths.GOODS_DETAIL + _Paths.MY_DISLIKES;
  static const MY_FOOTPRINT = _Paths.GOODS_DETAIL + _Paths.MY_FOOTPRINT;
  static const HEALTH_BUTLER = _Paths.GOODS_DETAIL + _Paths.HEALTH_BUTLER;
  static const HELP_AND_SERVICE = _Paths.GOODS_DETAIL + _Paths.HELP_AND_SERVICE;
  static const MY_INTEGRAL = _Paths.GOODS_DETAIL + _Paths.MY_INTEGRAL;
  static const MY_BALANCE = _Paths.MY_BALANCE;
  static const MY_GIFT_CARD = _Paths.MY_GIFT_CARD;
  static const MY_ORDER_DETAIL = _Paths.MY_ORDER_DETAIL;
  static const MY_REFUND_ORDER_DETAIL = _Paths.MY_REFUND_ORDER_DETAIL;
  static const APPRAISE_ORDER = _Paths.APPRAISE_ORDER;
  static const MY_REFUND_ORDER = _Paths.MY_REFUND_ORDER;
  static const BALANCE_USE_RECORD_LIST =
      _Paths.MY_GIFT_CARD + _Paths.BALANCE_USE_RECORD_LIST;
  static const MY_ACTIVITY_FORECAST = _Paths.MY_ACTIVITY_FORECAST;
  static const MY_VIP = _Paths.MY_VIP;
  static const MY_NOTICE_LIST = _Paths.MESSAGE_CENTER + _Paths.MY_NOTICE_LIST;
  static const ACCOUNT_INFO = _Paths.ACCOUNT_INFO;
  static const CHANGE_PHONE = _Paths.CHANGE_PHONE;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const CHANGE_GENDER = _Paths.CHANGE_GENDER;
  static const CHANGE_MEMBER_NAME = _Paths.CHANGE_MEMBER_NAME;
  static const CHANGE_MEMBER_AVATAR = _Paths.CHANGE_MEMBER_AVATAR;
  static const MY_PAY_PWD_MANAGE = _Paths.MY_PAY_PWD_MANAGE;
  static const CHANGE_PAY_PWD = _Paths.CHANGE_PAY_PWD;
  static const RESET_PAY_PWD = _Paths.RESET_PAY_PWD;
  static const FORGET_PAY_PWD = _Paths.FORGET_PAY_PWD;
  static const MY_WEBVIEW = _Paths.MY_WEBVIEW;
  static const MEIQIA_CHAT = _Paths.MESSAGE_CENTER + _Paths.MEIQIA_CHAT;
  static const FORGOT_PWD = _Paths.CHANGE_MEMBER_AVATAR + _Paths.FORGOT_PWD;
  static const SPLASH = _Paths.CHANGE_MEMBER_AVATAR + _Paths.SPLASH;
  static const BINDTEL = _Paths.BINDTEL;
  static const SET_PAY_PWD = _Paths.SET_PAY_PWD;
  static const FIND_DETAIL = _Paths.FIND_DETAIL;
  static const SHOP_CART = _Paths.SHOP_CART;
  static const SHARE_DETAIL = _Paths.FIELD_DETAIL + _Paths.SHARE_DETAIL;
  static const IMAGE_TEXT_UPLOAD = _Paths.IMAGE_TEXT_UPLOAD;
  static const VIDEO_UPLOAD = _Paths.VIDEO_UPLOAD;
  static const FOODIE_ARTICLES = _Paths.FOODIE_ARTICLES;
}

abstract class _Paths {
  _Paths._();

  static const ROOT = '/root';
  static const PRODUCT_INFO = '/product-info';

  //static const PRODUCT_LIST = '/product-list';
  static const LOGIN = '/login';
  static const SETTING = '/setting';
  static const REGISTER = '/register';
  static const ADDRESS_BOOK = '/address-book';
  static const ACCOUNT_SECURITY = '/account-security';
  static const PAYMENT_OPTIONS = '/payment-options';
  static const PRIVACY_POLICY = '/privacy-policy';
  static const LANGUAGE = '/language';
  static const COUNTRY_REGION = '/country-region';
  static const ABOUT_ME = '/about-me';
  static const ORDER_CONFIRM = '/order-confirm';
  static const ORDER_PAY = '/order-pay';
  static const ORDER_SUCCESS = '/order-success';
  static const MY_ORDER = '/my-order';
  static const ORDER_DELIVER = '/order-deliver';
  static const ORDER_DETAIL = '/order-detail';
  static const COMMENT = '/comment';
  static const COMMENT_DETAIL = '/comment-detail';
  static const MESSAGE_CENTER = '/message-center';
  static const MY_COMMENT = '/my-comment';
  static const LAND_LIST = '/land-list';
  static const OPERATION_RECORDS = '/operation-records';
  static const PROCESS = '/process';
  static const FIELD_DETAIL = '/field-detail';
  static const COMPLAINT_VIEW = '/complaint-view';
  static const REAL_TIME_LIST = '/real-time-list';
  static const LIVE_STREAMING = '/live-streaming';
  static const VR360 = '/vr360';
  static const REAL_TIME_PLAYER = '/real-time-player';
  static const SEARCH_VIEW = '/search-view';
  static const GOODS_DETAIL = '/goods-detail';
  static const ORDER_CHOOSE_COUPON = '/order-choose-coupon';
  static const ORDER_PAYMENT = '/order-payment';
  static const MY_ASSETS = '/my-assets';
  static const GUESS_LIKE = '/guess-like';
  static const MY_LIKES = '/my-likes';
  static const MY_DISLIKES = '/my-dislikes';
  static const MY_FOOTPRINT = '/my-footprint';
  static const HEALTH_BUTLER = '/health-butler';
  static const HELP_AND_SERVICE = '/help-and-service';
  static const MY_INTEGRAL = '/my-integral';
  static const MY_BALANCE = '/my-balance';
  static const MY_GIFT_CARD = '/my-gift-card';
  static const MY_ORDER_DETAIL = '/my-order-detail';
  static const MY_REFUND_ORDER_DETAIL = '/my-refund-order-detail';
  static const APPRAISE_ORDER = '/appraise-order';
  static const MY_REFUND_ORDER = '/my-refund-order';
  static const BALANCE_USE_RECORD_LIST = '/balance-use-record-list';
  static const MY_ACTIVITY_FORECAST = '/my-activity-forecast';
  static const MY_VIP = '/my-vip';
  static const MY_NOTICE_LIST = '/my-notice-list';
  static const ACCOUNT_INFO = '/account-info';
  static const CHANGE_PHONE = '/change-phone';
  static const CHANGE_PASSWORD = '/change-password';
  static const CHANGE_GENDER = '/change-gender';
  static const CHANGE_MEMBER_NAME = '/change-member-name';
  static const CHANGE_MEMBER_AVATAR = '/change-member-avatar';
  static const MY_PAY_PWD_MANAGE = '/my-pay-pwd-manage';
  static const CHANGE_PAY_PWD = '/change-pay-pwd';
  static const RESET_PAY_PWD = '/reset-pay-pwd';
  static const FORGET_PAY_PWD = '/forget-pay-pwd';
  static const MY_WEBVIEW = '/my-webview';
  static const MEIQIA_CHAT = '/meiqia-chat';
  static const FORGOT_PWD = '/forgot-pwd';
  static const SPLASH = '/splash';
  static const BINDTEL = '/bind-tel';
  static const SET_PAY_PWD = '/set-pay-pwd';
  static const FIND_DETAIL = '/find_detail';
  static const SHOP_CART = '/shop_cart';
  static const SHARE_DETAIL = '/share-detail';
  static const IMAGE_TEXT_UPLOAD = '/image-text-upload';
  static const VIDEO_UPLOAD = '/video-upload';
  static const FOODIE_ARTICLES = '/foodie-articles';
}
